server:
    port: 8090

spring:
    application:
        name: studants-service
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT:8761}/eureka

msg:
    error: mensagem final

